theme: jekyll-theme-cayman
url: https://alliee28.github.io/
baseurl: jk-assignment/
title: Test Jekyll site
description: This is my first Jekyll site
instagram: "https://www.instagram.com/allieepackard/?hl=en"
author: Alexandra Packard